-- 코드를 입력하세요
SELECT R.REST_ID,	REST_NAME,	FOOD_TYPE,	FAVORITES,	ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO I
JOIN REST_REVIEW R ON R.REST_ID = I.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY R.REST_ID
HAVING COUNT(R.REVIEW_SCORE) > 0
ORDER BY SCORE DESC, FAVORITES DESC