SELECT
    I.REST_ID,
    I.REST_NAME,
    I.FOOD_TYPE,
    I.FAVORITES,
    I.ADDRESS,
    ROUND(AVG(R.REVIEW_SCORE), 2) AS AVERAGE_SCORE
FROM
    REST_INFO I
JOIN
    REST_REVIEW R ON R.REST_ID = I.REST_ID
WHERE
    I.ADDRESS LIKE '서울%'
GROUP BY
    I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS
HAVING
    COUNT(R.REVIEW_SCORE) > 0 -- 리뷰가 있는 식당만 고려
ORDER BY
    AVERAGE_SCORE DESC,
    I.FAVORITES DESC;
