-- 코드를 입력하세요
SELECT
    PRODUCT_CODE,
    SUM(SALES_AMOUNT) * PRICE AS 'SALES'
FROM
    PRODUCT P
JOIN
    OFFLINE_SALE O ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    PRODUCT_CODE
ORDER BY
    SALES DESC,
    PRODUCT_CODE;