-- 코드를 입력하세요
SELECT B.AUTHOR_ID,	A.AUTHOR_NAME,	B.CATEGORY, SUM(BS.SALES * PRICE) AS TOTAL_SALES
FROM BOOK_SALES BS
JOIN BOOK B ON B.BOOK_ID = BS.BOOK_ID
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE DATE_FORMAT(BS.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY B.CATEGORY, A.AUTHOR_ID
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC